# Site settings
title: Bruno Sabença
email: eu@brunosabenca.com
description: ""
baseurl: ""
url: "http://brunosabenca.github.io"
username: brunosabenca

# Build settings
markdown: kramdown
permalink: pretty
